### ISSUE TITLE
What are sounds for and how do I use them?

### ISSUE THREAD

**Issue by lcb931023** [etohehir/bash-profile#1]
These are nice!

**Comment by SomniusTiger** [comment]
Oh, I've since removed the sounds from the repository – in a previous commit I had it so the Portal Turret would say "Activated" when I started a local rails server, and "Deploying" whenever I deployed via Capistrano. I decided against having them in there, since it was kind of annoying to have that play if I was in a public space or if I was listening to music.

If you wanted to still use them like I had in an older commit, however, go ahead and download them from here: http://theportalwiki.com/wiki/Turret_voice_lines and change their names to match the ones in the .bash_profile (the files seen right after the <code>afplay</code> command, this is the command that actually plays the sound). Then drop them in your Documents folder and you should be good to go!
